**Strassen’s Matrix Multiplication (Exploration)**

Given two square matrices of size A and B of size n * n, find their matrix multiplication. [Hint: Try to solve the given problem using the Divide and Conquer Approach]

**Median of Two Sorted Arrays (Apple)**

Given two sorted arrays num1 and num2 of size m and n respectively, return the median of the two sorted arrays.

**Pow(x,n) (Facebook)**

Implement pow(x,n) which calculates x raised to the power n (i.e. x^n)
For example: x = 2.00000, n = -2
Output: 0.25000
Explanation: 2^-2 =½^2 = ¼ = 0.25

**Divide Two Integers (Facebook)**

Given two integers, dividend and divisor, divide the two integers without using multiplication, division, and mod operator.


In [19]:
# Median of two sorted arrays
# Running time complexity will be O(n+m)

def medianarrays(arr1, arr2):
    i = 0
    j = 0
    m1 = 0
    m2 = 0
    n1 = len(arr1)
    n2 = len(arr2)
    
    for k in range(((n1+n2)//2)+ 1):
        if (i != n1 and j != n2):
            if arr1[i] > arr2[j]:
                m1 = arr2[j]
                j +=1
            else:
                m1 = arr1[i]
                i += 1
        elif (i < n1):
            m1 = arr1[i]
            i += 1
        else:
            m1 = arr2[j]
            j += 1
        
    if (n1 + n2)% 2 == 1:
        return m1
    else:
        return (m1 + m2)//2
            

if __name__=="__main__":
    arr1 = [20,25,30,35,40,45,47]
    arr2 = [15, 19, 22, 33, 36, 50]
    
    median_arrays = medianarrays(arr1, arr2)
    print("Median of Two sorted arrays is: ", median_arrays)

Median of Two sorted arrays is:  33


In [6]:
#Finding the power of an element using recursive approach.
# Running time will be O(log n)

def powerelement(a, n):
    if n==0:
        return 1
    elif n==1:
        return a
    elif n < 0:
        a = 1/a
        n = -n
        return powerelement(a, n)
    else:
        mid = n//2
        b = powerelement(a, mid)
        power = b * b
        if n % 2 == 0:
            return power
        else:
            return power * a
    return -1
if __name__ == "__main__":
    a = 2
    n = 4
    power_ele = powerelement(a, n)
    print("{} Power {} is {}".format(a, n, power_ele))

2 Power 4 is 16


In [8]:
# Strassen’s Matrix Multiplication
# Running time will O(n^2.81)

import numpy as np

def divide(matrix):
    rows, columns = matrix.shape
    row1, column1 = rows//2, columns//2
    return matrix[:row1, :column1], matrix[:row1, column1:], matrix[row1:, :column1], matrix[row1:, column1:]
    
def strassen_multi(A, B):
    
    if len(A) == 1:
        return A * B
    
    a, b, c, d = divide(A)
    e, f, g, h = divide(B)
    
    p1 = strassen_multi(a, f - h)
    p2 = strassen_multi(a + b, h)
    p3 = strassen_multi(c + d, e)
    p4 = strassen_multi(d, g - e)
    p5 = strassen_multi(a + d, e + h)
    p6 = strassen_multi(b - d, g + h)
    p7 = strassen_multi(a - c, e + f)
    
    c11 = p5 + p4 - p2 + p6
    c12 = p1 + p2
    c21 = p3 + p4
    c22 = p1 + p5 - p3 - p7
    
    c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))
    
    return c
    

if __name__=="__main__":
    A = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[1,3,5,7]])
    B = np.array([[2,3,4,5],[3,4,5,6],[4,5,6,7],[7,5,3,1]])
    print("Matrix Multiplication:")
    print(strassen_multi(A, B))
    



Matrix Multiplication:
[[48 46 44 42]
 [64 63 62 61]
 [80 80 80 80]
 [80 75 70 65]]


In [9]:
# Divide two integers without using dividing, multipication and modulo operator.
# Running time will be O(n)

def division_two_int(dividend, divisor):
    
    divid = abs(dividend)
    divis = abs(divisor)
    
    result = 0
    while divid >= divis:
        shift = 0
        while divid >= (divis << shift):
            shift += 1
            result += (1 << (shift - 1))
            divid -= divis << (shift - 1)
            
            if (divid < 0 and divis >= 0) or (divis < 0 and divid >= 0):
                result -= result
                
    return min(21472483647, max(-21472483647, result))

if __name__ == "__main__":
    div = division_two_int(16, 2)
    print("The division of two integers will be {}".format(div))

The division of two integers will be 8
